### ISSUE TITLE
Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by Trojaner** [bruceadams/get-release#4]
```
Error: Parameter token or opts.auth is required
    at Function.getAuthString (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:7018:19)
    at Function.getOctokitOptions (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:6983:29)
    at new GitHub (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:6967:22)
    at run (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:24720:20)
    at Object.31 (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:397:3)
    at __webpack_require__ (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:37:19)
    at /home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/bruceadams/get-release/v1.2.0/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
##[error]Parameter token or opts.auth is required
```

**Comment by Gerrit91** [comment]
I could resolve this issue by passing the `GITHUB_TOKEN` in the environment:

```
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
