### ISSUE TITLE
Unable to get tag_name

### ISSUE THREAD

**Issue by juzi5201314** [bruceadams/get-release#8]
```
      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/bin
          asset_name: tag-${{ steps.get_release.outputs.tag_name }}-bin
          asset_content_type: application/octet-stream
```

Get a `tag--bin`
